USE DB_T2_DIONISIO_JUNIOR;

/* ---------------------------------------------------------------------------------------------------------------*/
/* CRIANDO TABELAS */

DESCRIBE TB_CUSTOMERS_FINAL;
DESCRIBE TB_PETS_FINAL;
DESCRIBE TB_RENTS_FINAL;
DESCRIBE TB_LOGS_FINAL;

CREATE TABLE TB_CUSTOMERS_FINAL ( 
 ID_CUSTOMER INT PRIMARY KEY AUTO_INCREMENT,  
 NAME_CUSTOMER VARCHAR(200) NOT NULL,  
 TYPE_CUSTOMER VARCHAR(200) NOT NULL
); 

CREATE TABLE TB_PETS_FINAL ( 
	 ID_PET INT PRIMARY KEY AUTO_INCREMENT,
	 NAME_PET VARCHAR(200) NOT NULL,  
	 TYPE_PET VARCHAR(200) NOT NULL,
	 AVAILABLE BOOLEAN NOT NULL  
); 

CREATE TABLE TB_RENTS_FINAL ( 
	ID_RENT INT PRIMARY KEY AUTO_INCREMENT,
	HOURS INT NOT NULL,  
	PRICE_PER_HOUR DECIMAL(10,2) NOT NULL,  
	TOTAL_VALUE INT NOT NULL,  
	START_DATE DATETIME NOT NULL,  
	END_DATE DATETIME NOT NULL,  
	DATE_RENT DATETIME NOT NULL,  
 
 /* CHAVES ESTRANGEIRAS */
	ID_CUSTOMER INT,
	FOREIGN KEY (ID_CUSTOMER) REFERENCES TB_CUSTOMERS_FINAL (ID_CUSTOMER),
	ID_PET INT,
	FOREIGN KEY (ID_PET) REFERENCES TB_PETS_FINAL (ID_PET)
); 

CREATE TABLE TB_LOGS_FINAL ( 
	ID_LOG INT PRIMARY KEY AUTO_INCREMENT,  
	CREATED_AT DATETIME NOT NULL,  
	TABLE_NAME VARCHAR(200) NOT NULL,  
	ACTION VARCHAR(200) NOT NULL,  
	OLD_VALUE VARCHAR(200) NOT NULL,  
	NEW_VALUE VARCHAR(200) NOT NULL,  

/* CHAVES ESTRANGEIRAS */
	ID_CUSTOMER INT,
	FOREIGN KEY (ID_CUSTOMER) REFERENCES TB_CUSTOMERS_FINAL (ID_CUSTOMER),
	ID_PET INT,
	FOREIGN KEY (ID_PET) REFERENCES TB_PETS_FINAL (ID_PET),
	ID_RENT INT,
    FOREIGN KEY (ID_RENT) REFERENCES TB_RENTS_FINAL (ID_RENT)
); 

/* ---------------------------------------------------------------------------------------------------------------*/
/* INSERINDO DADOS NAS TABELAS */

INSERT INTO TB_CUSTOMERS_FINAL (NAME_CUSTOMER, TYPE_CUSTOMER) 
VALUES 
	('Ana Silva', 'Física'), ('Bruno Souza', 'Física'), ('Carla Dias', 'Física'),
	('Daniel Oliveira', 'Física'), ('Eduarda Lima', 'Física'), ('Fábio Santos', 'Física'),
	('Gabriel Costa', 'Física'), ('Helena Rocha', 'Física'), ('Igor Mendes', 'Física'),
	('Julia Ferraz', 'Física');

INSERT INTO TB_PETS_FINAL (NAME_PET, TYPE_PET, AVAILABLE) 
VALUES 
	('Rex', 'Cachorro', TRUE), ('Mingau', 'Gato', TRUE), ('Thor', 'Cachorro', TRUE),
	('Luna', 'Gato', FALSE), ('Bidu', 'Cachorro', TRUE), ('Mel', 'Gato', TRUE),
	('Frederico', 'Hamster', TRUE), ('Pipoca', 'Coelho', FALSE), ('Simba', 'Leão', TRUE),
	('Paçoca', 'Cachorro', TRUE);

INSERT INTO TB_RENTS_FINAL (HOURS, PRICE_PER_HOUR, TOTAL_VALUE, START_DATE, END_DATE, DATE_RENT, ID_CUSTOMER, ID_PET) 
VALUES 
	(2, 50.00, 100, '2023-10-01 10:00:00', '2023-10-01 12:00:00', '2023-10-01 09:30:00', 1, 1),
	(3, 40.00, 120, '2023-10-02 14:00:00', '2023-10-02 17:00:00', '2023-10-02 13:45:00', 2, 2),
	(1, 60.00, 60, '2023-10-03 09:00:00', '2023-10-03 10:00:00', '2023-10-03 08:50:00', 3, 3),
	(4, 35.00, 140, '2023-10-04 15:00:00', '2023-10-04 19:00:00', '2023-10-04 14:30:00', 4, 5),
	(2, 50.00, 100, '2023-10-05 10:00:00', '2023-10-05 12:00:00', '2023-10-05 09:55:00', 5, 6),
	(5, 30.00, 150, '2023-10-06 08:00:00', '2023-10-06 13:00:00', '2023-10-06 07:45:00', 6, 7),
	(2, 45.00, 90, '2023-10-07 16:00:00', '2023-10-07 18:00:00', '2023-10-07 15:50:00', 7, 9),
	(3, 50.00, 150, '2023-10-08 11:00:00', '2023-10-08 14:00:00', '2023-10-08 10:40:00', 8, 10),
	(1, 70.00, 70, '2023-10-09 13:00:00', '2023-10-09 14:00:00', '2023-10-09 12:55:00', 9, 1),
	(2, 55.00, 110, '2023-10-10 10:00:00', '2023-10-10 12:00:00', '2023-10-10 09:50:00', 10, 3);

INSERT INTO TB_LOGS_FINAL (CREATED_AT, TABLE_NAME, ACTION, OLD_VALUE, NEW_VALUE, ID_CUSTOMER, ID_PET, ID_RENT) 
VALUES 
	(NOW(), 'TB_PETS_FINAL', 'UPDATE', 'AVAILABLE: TRUE', 'AVAILABLE: FALSE', NULL, 4, NULL),
	(NOW(), 'TB_CUSTOMERS_FINAL', 'INSERT', 'NULL', 'Ana Silva', 1, NULL, NULL),
	(NOW(), 'TB_RENTS_FINAL', 'INSERT', 'NULL', 'New Rent ID: 1', 1, 1, 1),
	(NOW(), 'TB_PETS_FINAL', 'UPDATE', 'AVAILABLE: TRUE', 'AVAILABLE: FALSE', NULL, 8, NULL),
	(NOW(), 'TB_RENTS_FINAL', 'INSERT', 'NULL', 'New Rent ID: 2', 2, 2, 2),
	(NOW(), 'TB_CUSTOMERS_FINAL', 'UPDATE', 'TYPE: Física', 'TYPE: VIP', 3, NULL, NULL),
	(NOW(), 'TB_RENTS_FINAL', 'INSERT', 'NULL', 'New Rent ID: 3', 3, 3, 3),
	(NOW(), 'TB_PETS_FINAL', 'INSERT', 'NULL', 'Paçoca', NULL, 10, NULL),
	(NOW(), 'TB_RENTS_FINAL', 'DELETE', 'Rent ID: 10', 'Archived', 10, 3, 10),
	(NOW(), 'TB_CUSTOMERS_FINAL', 'INSERT', 'NULL', 'Julia Ferraz', 10, NULL, NULL);

/* ---------------------------------------------------------------------------------------------------------------*/
/* TESTES */
SELECT * FROM JN_CAR;
SELECT * FROM JN_CUSTOMER;
SELECT * FROM JN_SALE;

TRUNCATE JN_CAR;
TRUNCATE JN_CUSTOMER;
TRUNCATE JN_SALE;

DROP TABLE JN_CAR;
DROP TABLE JN_CUSTOMER;
DROP TABLE JN_SALE;

/* ---------------------------------------------------------------------------------------------------------------*/
/* FAZENDO OS SELECTS - PARTE 1 */

/* ---------------------------------------------------------------------------------------------------------------*/
/* GERANDO PROCEDURES PARA INSERIR */

/* GERANDO PROCEDURES PARA DELETAR */

/* GERANDO PROCEDURES PARA CONSULTAR POR ID */


/* ---------------------------------------------------------------------------------------------------------------*/
/* TESTANDO PROCEDURES */
USE DB_T2_DIONISIO_JUNIOR_DANDANINVESTIMENTOS;

CALL P_INSERT_CONT_CUSTOMERS('TESTEPROCEDURE', '1993-11-15', 'BRAZIL', 500.00);
CALL P_DELET_CONT_CUSTOMERS(202);
CALL P_SELECT_CONT_CUSTOMERS(102);

SELECT * FROM CONT_CUSTOMERS;
/*
DROP PROCEDURE IF EXISTS P_CONT_INSERT_CUSTOMERS;
*/


/* ---------------------------------------------------------------------------------------------------------------*/
/* GERANDO TRIGGERS PARA REGISTROS DE LOG */
/* GERANDO TRIGGERS PARA INSERIR - {BEFORE | AFTER } {INSERT | UPDATE | DELETE} */

/* GERANDO TRIGGERS PARA UPDATE - {BEFORE | AFTER } {INSERT | UPDATE | DELETE} */

/* GERANDO TRIGGERS PARA DELETE - {BEFORE | AFTER } {INSERT | UPDATE | DELETE} */


/*DROP TRIGGER IF EXISTS TRG_AFTER_DELETE_ACCOUNT;*/


/* ---------------------------------------------------------------------------------------------------------------*/
/* TESTES */
USE DB_T2_DIONISIO_JUNIOR;

SELECT * FROM CONT_CUSTOMERS;
SELECT * FROM CONT_PRODUCTS;

DESCRIBE CONT_CUSTOMERS;
DESCRIBE CONT_PRODUCTS;
DESCRIBE CONT_INVESTIMENTS;

/*
TRUNCATE CONT_CUSTOMERS;
TRUNCATE CONT_PRODUCTS;
TRUNCATE CONT_INVESTIMENTS;
TRUNCATE CONT_COSTS;
TRUNCATE CONT_LOG;

DROP TABLE CONT_CUSTOMERS;
DROP TABLE CONT_PRODUCTS;
DROP TABLE CONT_INVESTIMENTS;
DROP TABLE CONT_COSTS;
DROP TABLE CONT_LOG;
*/
