USE DB_T2_DIONISIO_JUNIOR;

/* ---------------------------------------------------------------------------------------------------------------*/
/* CRIANDO TABELAS */

CREATE TABLE IF NOT EXISTS TB_CUSTOMERS_FINAL ( 
	ID_CUSTOMER INT PRIMARY KEY AUTO_INCREMENT,  
	NAME_CUSTOMER VARCHAR(200) NOT NULL,  
	TYPE_CUSTOMER VARCHAR(200) NOT NULL
); 

CREATE TABLE IF NOT EXISTS TB_PETS_FINAL ( 
	 ID_PET INT PRIMARY KEY AUTO_INCREMENT,
	 NAME_PET VARCHAR(200) NOT NULL,  
	 TYPE_PET VARCHAR(200) NOT NULL,
     AGE_PET INT NOT NULL,
	 AVAILABLE BOOLEAN NOT NULL
); 

CREATE TABLE IF NOT EXISTS TB_RENTS_FINAL ( 
	ID_RENT INT PRIMARY KEY AUTO_INCREMENT,
	HOURS INT NOT NULL,  
	PRICE_PER_HOUR DECIMAL(10,2) NOT NULL,  
	TOTAL_VALUE INT NOT NULL,  
	START_DATE DATETIME NOT NULL,  
	END_DATE DATETIME NOT NULL,  
	DATE_RENT DATETIME NOT NULL,  
 
/* CHAVES ESTRANGEIRAS */
	ID_CUSTOMER INT NOT NULL,
	FOREIGN KEY (ID_CUSTOMER) REFERENCES TB_CUSTOMERS_FINAL (ID_CUSTOMER),
	ID_PET INT NOT NULL,
	FOREIGN KEY (ID_PET) REFERENCES TB_PETS_FINAL (ID_PET)
); 

CREATE TABLE IF NOT EXISTS TB_LOGS_FINAL ( 
	ID_LOG INT PRIMARY KEY AUTO_INCREMENT,  
	CREATED_AT DATETIME NOT NULL,  
	TABLE_NAME VARCHAR(200) NOT NULL,  
	ACTION VARCHAR(200) NOT NULL,  
	OLD_VALUE VARCHAR(200) NOT NULL,  
	NEW_VALUE VARCHAR(200) NOT NULL,  

/* CHAVES ESTRANGEIRAS */
	ID_CUSTOMER INT NOT NULL,
	FOREIGN KEY (ID_CUSTOMER) REFERENCES TB_CUSTOMERS_FINAL (ID_CUSTOMER),
	ID_PET INT NOT NULL,
	FOREIGN KEY (ID_PET) REFERENCES TB_PETS_FINAL (ID_PET),
	ID_RENT INT NOT NULL,
    FOREIGN KEY (ID_RENT) REFERENCES TB_RENTS_FINAL (ID_RENT)
); 

/* ---------------------------------------------------------------------------------------------------------------*/
/* INSERINDO DADOS NAS TABELAS */
USE DB_T2_DIONISIO_JUNIOR;

INSERT INTO TB_CUSTOMERS_FINAL (NAME_CUSTOMER, TYPE_CUSTOMER) 
VALUES 
	('Ana Silva', 'Person'), 
    ('Hospital Vida', 'Company'), 
    ('Joâo Souza', 'Person'),
	('Daniel Oliveira', 'Person'), 
    ('Hospital São Paulo', 'Company'), 
    ('Fábio Santos', 'Person'),
	('Hospital Guarulhos', 'Company'), 
    ('Helena Rocha', 'Person'), 
    ('Igor Mendes', 'Person'),
	('Hospital Rio de Janeiro', 'Company');

INSERT INTO TB_PETS_FINAL (NAME_PET, TYPE_PET, AGE_PET, AVAILABLE) 
VALUES 
	('Rex', 'Cachorro', 3, TRUE),      
	('Luna', 'Cachorro', 2, FALSE),
    ('Thor', 'Cachorro', 5, TRUE),
    ('Mingau', 'Gato', 7, TRUE),
    ('Bidu', 'Cachorro', 10, TRUE), 
    ('Mel', 'Gato', 4, TRUE),
	('Frederico', 'Cachorro', 11, TRUE), 
    ('Pipoca', 'Gato', 6, FALSE), 
    ('Simba', 'Cachorro', 9, TRUE),
	('Paçoca', 'Gato', 12, TRUE);

INSERT INTO TB_RENTS_FINAL (HOURS, PRICE_PER_HOUR, TOTAL_VALUE, START_DATE, END_DATE, DATE_RENT, ID_CUSTOMER, ID_PET) 
VALUES 
	(2, 50.00, 100, '2023-10-01 10:00:00', '2023-10-01 12:00:00', '2023-10-01 09:30:00', 1, 1),
	(3, 40.00, 120, '2023-10-02 14:00:00', '2023-10-02 17:00:00', '2023-10-02 13:45:00', 2, 2),
	(1, 60.00, 60, '2023-10-03 09:00:00', '2023-10-03 10:00:00', '2023-10-03 08:50:00', 3, 3),
	(4, 35.00, 140, '2023-10-04 15:00:00', '2023-10-04 19:00:00', '2023-10-04 14:30:00', 4, 5),
	(2, 50.00, 100, '2023-10-05 10:00:00', '2023-10-05 12:00:00', '2023-10-05 09:55:00', 5, 6),
	(5, 30.00, 150, '2023-10-06 08:00:00', '2023-10-06 13:00:00', '2023-10-06 07:45:00', 6, 7),
	(2, 45.00, 90, '2023-10-07 16:00:00', '2023-10-07 18:00:00', '2023-10-07 15:50:00', 7, 9),
	(3, 50.00, 150, '2023-10-08 11:00:00', '2023-10-08 14:00:00', '2023-10-08 10:40:00', 8, 10),
	(1, 70.00, 70, '2023-10-09 13:00:00', '2023-10-09 14:00:00', '2023-10-09 12:55:00', 9, 1),
	(2, 55.00, 110, '2023-10-10 10:00:00', '2023-10-10 12:00:00', '2023-10-10 09:50:00', 10, 3),
	(21310, 55.00, 1172050, NOW(), '2028-10-10 09:50:00', NOW(), 10, 1),
    (35063, 55.00, 1928465, '2025-10-10 10:00:00', '2029-10-10 09:50:00', NOW(), 10, 2);

INSERT INTO TB_LOGS_FINAL (CREATED_AT, TABLE_NAME, ACTION, OLD_VALUE, NEW_VALUE, ID_CUSTOMER, ID_PET, ID_RENT) 
VALUES 
	(NOW(), 'TB_RENTS_FINAL', 'INSERT', 'NONE', 'NEW_RENT_CREATED', 1, 1, 1),
	(NOW(), 'TB_RENTS_FINAL', 'UPDATE', 'STATUS: PENDING', 'STATUS: ACTIVE', 2, 2, 2),
	(NOW(), 'TB_RENTS_FINAL', 'UPDATE', 'HOURS: 1', 'HOURS: 2', 3, 3, 3),
	(NOW(), 'TB_PETS_FINAL', 'STATUS_CHANGE', 'AVAILABLE: 1', 'AVAILABLE: 0', 4, 5, 4),
	(NOW(), 'TB_RENTS_FINAL', 'PAYMENT', 'PAID: 0', 'PAID: 1', 5, 6, 5),
	(NOW(), 'TB_RENTS_FINAL', 'RENEWAL', 'END_DATE: 2023-10-06', 'END_DATE: 2023-10-07', 6, 7, 6),
	(NOW(), 'TB_CUSTOMERS_FINAL', 'DISCOUNT_APPLIED', 'TOTAL: 90', 'TOTAL: 81', 7, 9, 7),
	(NOW(), 'TB_RENTS_FINAL', 'UPDATE', 'PRICE: 50', 'PRICE: 55', 8, 10, 8),
	(NOW(), 'TB_PETS_FINAL', 'CHECK_IN', 'AVAILABLE: 0', 'AVAILABLE: 1', 9, 1, 9),
	(NOW(), 'TB_RENTS_FINAL', 'FINALIZATION', 'STATUS: OPEN', 'STATUS: CLOSED', 10, 3, 10);

/* ---------------------------------------------------------------------------------------------------------------*/
/* FAZENDO OS SELECTS */
/* 1. Qual é o faturamento total do sistema? */
SELECT
	SUM(TB_RENTS_FINAL.TOTAL_VALUE) AS Valor_Total
FROM TB_RENTS_FINAL;


/* 2. Quanto cada cliente já gastou? */
SELECT
	TB_CUSTOMERS_FINAL.NAME_CUSTOMER AS Cliente,
	SUM(TB_RENTS_FINAL.TOTAL_VALUE) AS Total_Por_Cliente
FROM TB_CUSTOMERS_FINAL
	INNER JOIN TB_RENTS_FINAL
		ON TB_CUSTOMERS_FINAL.ID_CUSTOMER = TB_RENTS_FINAL.ID_CUSTOMER
	GROUP BY Cliente
	ORDER BY Total_Por_Cliente DESC;
		
        
/* 3. Qual animal foi mais alugado? */
SELECT 
    TB_PETS_FINAL.NAME_PET AS Nome_Pet,
    COUNT(TB_RENTS_FINAL.ID_RENT) AS Total_Alugueis
FROM TB_PETS_FINAL
	INNER JOIN TB_RENTS_FINAL
		ON TB_PETS_FINAL.ID_PET = TB_RENTS_FINAL.ID_PET
	GROUP BY Nome_Pet
    ORDER BY Total_Alugueis DESC
    LIMIT 1;
    
    
/* 4. Quais aluguéis estão ativos? */
SELECT
	TB_CUSTOMERS_FINAL.NAME_CUSTOMER AS Nome_Cliente,
    TB_PETS_FINAL.NAME_PET AS Nome_do_Pet,
    TB_RENTS_FINAL.START_DATE AS Data_Inicío,
    TB_RENTS_FINAL.END_DATE AS Data_Fim
FROM TB_RENTS_FINAL
	INNER JOIN TB_CUSTOMERS_FINAL
		ON TB_CUSTOMERS_FINAL.ID_CUSTOMER = TB_RENTS_FINAL.ID_CUSTOMER
	INNER JOIN TB_PETS_FINAL
		ON TB_PETS_FINAL.ID_PET = TB_RENTS_FINAL.ID_PET
	WHERE NOW() BETWEEN TB_RENTS_FINAL.START_DATE AND TB_RENTS_FINAL.END_DATE;

/* ---------------------------------------------------------------------------------------------------------------*/
/* RESPONDENDO AS PERGUNTAS */

/* 5. Como melhorar o faturamento do app? 
Resposta: Criar programas de fidelidade para os clientes que fazem alugúeis com recorrência.
*/

/* 6. Como fazer mais pessoas usarem o app? 
Resposta: Criar campanhas online, nos sites e redes sociais de instituições de caridade, além de dar descontos para que indica.
*/

/* 7. Como melhorar a experiência do cliente? 
Resposta: Para os clinetes que já usam o aplicativo, seria interessante exibir um opção para repetir o mesmo aluguél, 
para evitar que ele preencha tudo de novo.
*/

/* 8. Como tornar o app mais confiável para empresas? 
Resposta: Considerando que os clientes poderão realizar apenas aluguéis pelo aplicativo, foi criado um sistema de logs, 
para garantir o controle das solicitações feitas por eles.
*/

/* ---------------------------------------------------------------------------------------------------------------*/
/* GERANDO PROCEDURE PARA INSERIR ALUGUEL E CALCULAR AUTOMATICAMENTE O PREÇO DAS HORAS */

DELIMITER //
CREATE PROCEDURE P_INSERT_TB_RENTS_FINAL (  
    IN P_ID_CUSTOMER INT, 
    IN P_ID_PET INT, 
    IN P_PRICE_PER_HOUR DECIMAL(10,2), 
    IN P_START_DATE DATETIME, 
    IN P_END_DATE DATETIME
)
BEGIN
	/* DECLARANDO VARIÁVEIS */
	DECLARE var_hours INT;
	DECLARE var_total_value DECIMAL(10,2);

	/* CALCULANDO AS HORAS INTEIRAS (ARREDONDANDO) ENTRE DATAS */
	SET var_hours = TIMESTAMPDIFF(HOUR, P_START_DATE, P_END_DATE);
	
	/* CALCULANDO VALOR TOTAL */
	SET var_total_value = var_hours * P_PRICE_PER_HOUR;

	INSERT INTO TB_RENTS_FINAL (HOURS, PRICE_PER_HOUR, TOTAL_VALUE, START_DATE, END_DATE, DATE_RENT, ID_CUSTOMER, ID_PET)

		/* INSERINDO VALORES CALCULADOS */
		VALUES (var_hours, P_PRICE_PER_HOUR, var_total_value, P_START_DATE, P_END_DATE, NOW(), P_ID_CUSTOMER, P_ID_PET);
END //
DELIMITER ;
/* DROP PROCEDURE IF EXISTS P_INSERT_TB_RENTS_FINAL; */

/* ---------------------------------------------------------------------------------------------------------------*/
/* GERANDO TRIGGERS PARA REGISTROS DE LOG */

/* GATILHO INSERT */
DELIMITER //
CREATE TRIGGER TRG_LOG_INSERT_RENT
	AFTER INSERT ON TB_RENTS_FINAL
	FOR EACH ROW
BEGIN
    INSERT INTO TB_LOGS_FINAL (CREATED_AT, TABLE_NAME, ACTION, OLD_VALUE, NEW_VALUE, ID_CUSTOMER, ID_PET, ID_RENT)
		VALUES (
			NOW(), 
			'TB_RENTS_FINAL', 
			'INSERT', 
			'N/A', /* COMO ESTÁ INSERINDO DADOS NOVOS, ESSE CAMPO SEMPRE FICA SEM DADOS ANTERIORES */
			CONCAT('Novo Aluguel: ', NEW.ID_RENT, ' | Valor: ', NEW.TOTAL_VALUE), 
			NEW.ID_CUSTOMER, 
			NEW.ID_PET, 
			NEW.ID_RENT
		);
END //
DELIMITER ;
/* DROP TRIGGER IF EXISTS TRG_LOG_INSERT_RENT; */

/* ---------------------------------------------------------------------------------------------------------------*/
/* TESTES */

USE DB_T2_DIONISIO_JUNIOR;

DESCRIBE TB_CUSTOMERS_FINAL;
DESCRIBE TB_PETS_FINAL;
DESCRIBE TB_RENTS_FINAL;
DESCRIBE TB_LOGS_FINAL;

SELECT * FROM TB_CUSTOMERS_FINAL;
SELECT * FROM TB_PETS_FINAL;
SELECT * FROM TB_RENTS_FINAL;
SELECT * FROM TB_LOGS_FINAL;

/*
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TB_CUSTOMERS_FINAL;
TRUNCATE TB_PETS_FINAL;
TRUNCATE TB_RENTS_FINAL;
TRUNCATE TB_LOGS_FINAL;

SET FOREIGN_KEY_CHECKS = 1;
*/
/*
DROP TABLE TB_CUSTOMERS_FINAL;
DROP TABLE TB_PETS_FINAL;
DROP TABLE TB_RENTS_FINAL;
DROP TABLE TB_LOGS_FINAL;
*/

/* TESTANDO PROCEDURE ( ID_CUSTOMER, ID_PET, PRICE_PER_HOUR, START_DATE, END_DATE ) */

CALL P_INSERT_TB_RENTS_FINAL(10, 9, 55.00, NOW(), '2029-10-10 09:50:00');
CALL P_INSERT_TB_RENTS_FINAL(10, 8, 55.00, NOW(), '2028-10-10 09:50:00');
CALL P_INSERT_TB_RENTS_FINAL(10, 8, 55.00, NOW(), '2028-10-10 09:50:00');

SELECT * FROM TB_RENTS_FINAL ORDER BY ID_RENT DESC;

/* AO RODAR A PROCEDURE PARA INSERIR, 1 LOG É REGISTRADO */
SELECT * FROM TB_LOGS_FINAL ORDER BY CREATED_AT DESC;